# Site settings
title: Dịch vụ nấu ăn tại nhà ở Đà Nẵng | Thực đơn đa dạng | Giá cả hợp lý
description: "Dịch vụ nấu tiệc tại nhà ở ĐÀ NẴNG - Nhận Nấu Ăn, Đặt Tiệc Tân Gia, Nhà Mới, Cưới Hỏi, Thôi Nôi, Tất Niên - GIÁ TỪ 90.000đ/ SUẤT"
url: "http://thuybodanang.com"
author:
  # name: "The Review Index"
  # email: "dyutibarma@gmail.com"
  # url: "https://thereviewindex.com"

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier


# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
